run:
    privileged: true
    user: root
    build: .
    environment:
        JAVA_OPTS: -Djava.util.logging.config.file=/var/jenkins_home/log.properties
    ports:
        - 8000:8080
        - 5000:5000
    volumes:
        - /jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock